### ISSUE TITLE
build it in kernel 3.8.13

### ISSUE THREAD

**Issue by lichaowuwei** [bwilcutt/encx24j600#1]
can i build it with kernel 3.8.13-xenomai?
when i build it , there is some error
appriciate your reply~~

**Comment by bwilcutt** [comment]
Honestly, I dont know.  The driver model hasnt really changed so I would suspect it should work fine.
Bryan

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 1, 2019 at 4:27 AM, lichaowuwei<notifications@github.com> wrote:   
can i build it with kernel 3.8.13-xenomai?
when i build it , there is some error
appriciate your reply~~
